services:

  # ============================================================
  # PostgreSQL
  # Banco de dados principal do SUS Connect
  # ============================================================
  postgres:
    image: postgres:16
    container_name: sus-connect-postgres

    restart: always

    environment:
      POSTGRES_DB: sus_connect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  # ============================================================
  # Apache Kafka
  # Broker de eventos utilizado pela arquitetura Event Driven
  # ============================================================
  kafka:
    image: apache/kafka:3.9.1
    container_name: sus-connect-kafka

    restart: always

    ports:
      - "9092:9092"

    environment:

      # Identificador do nó Kafka
      KAFKA_NODE_ID: 1

      # Kafka utilizando KRaft:
      # o mesmo nó atua como broker e controller
      KAFKA_PROCESS_ROLES: broker,controller

      # Configuração do quorum do controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners internos do Kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      # Endereço utilizado pela aplicação Spring Boot,
      # executada localmente fora do Docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # Protocolos utilizados pelos listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Listener responsável pelo controller KRaft
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Comunicação entre brokers
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Como o MVP utiliza apenas um broker,
      # os fatores de replicação precisam ser 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


# ==============================================================
# Volumes persistentes
# ==============================================================
volumes:

  postgres_data: