spring:

  application:
    name: SUS Connect API

  # ============================================================
  # PostgreSQL
  # ============================================================
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sus_connect}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  # ============================================================
  # JPA / Hibernate
  # ============================================================
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  # ============================================================
  # Jackson
  # ============================================================
  jackson:
    time-zone: America/Sao_Paulo

  # ============================================================
  # Apache Kafka
  # ============================================================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: sus-connect
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "br.com.susconnect.*"


# ==============================================================
# Servidor
# ==============================================================
server:
  port: 8080


# ==============================================================
# Swagger / OpenAPI
# ==============================================================
springdoc:
  swagger-ui:
    path: /swagger


# ==============================================================
# Logging
# ==============================================================
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG


# ==============================================================
# Machine Learning - Predição de risco de No-Show
# ==============================================================
sus-connect:

  ml:
    base-url: ${ML_BASE_URL:http://localhost:8000}